on:
  push:
    branches:
      - main
  pull_request:

name: Integration
jobs:
  type-check:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [18.x]
      steps:
        - uses: actions/checkout@v3
        - name: Setup pnpm
          uses: pnpm/action-setup@v2

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'pnpm'
        - run: pnpm install

        - name: Type Check
          run: pnpm tsc --noEmit

        - name: Lint Check
          run: pnpm eslint .
